In [1]:
#Importando librerias
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import confusion_matrix
from sklearn.cluster import KMeans
from scipy import stats
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier as forest

### Separación y Validación para algoritmos de ML

### Preparación de del DataSet

In [2]:
# Precio del Oro de 2013 a 2023
df = pd.read_csv('Gold Price (2013-2023) (2).csv')
df.head(1)

         Date     Price      Open      High       Low     Vol. Change %
0  12/30/2022  1,826.20  1,821.80  1,832.40  1,819.80  107.50K    0.01%

In [3]:
# Quitando las columnas de Vol y Change, ya que no se utilizaran.
df.drop(['Vol.', 'Change %'], axis=1, inplace=True)
df.head(1)

         Date     Price      Open      High       Low
0  12/30/2022  1,826.20  1,821.80  1,832.40  1,819.80

In [4]:
#Identificación de datos, son objetos, por lo que se tienen que cambiar a valores que corresponden a cada columna.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2583 entries, 0 to 2582
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2583 non-null   object
 1   Price   2583 non-null   object
 2   Open    2583 non-null   object
 3   High    2583 non-null   object
 4   Low     2583 non-null   object
dtypes: object(5)
memory usage: 101.0+ KB

In [5]:
df['Date'] = pd.to_datetime(df['Date'])
df.sort_values(by='Date', ascending =True, inplace=True)
df.reset_index(drop=True, inplace=True)
df.head(1)

        Date     Price      Open      High       Low
0 2013-01-02  1,689.90  1,675.80  1,695.00  1,672.10

In [6]:
#Buscando datos duplicados:
df.duplicated().sum()

0

In [7]:
#Buscando celdas vacias:
df.isnull().sum().sum()

0

In [8]:
#Traduciendo las columnas:
column_name_mapping = {
    'Date' : 'Fecha' ,
    'Price' : 'Precio',
    'Open': 'Apertura',
    'High': 'Máximo',
    'Low': 'Mínimo',
}
df = df.rename(columns = column_name_mapping)

df.head(1)

       Fecha    Precio  Apertura    Máximo    Mínimo
0 2013-01-02  1,689.90  1,675.80  1,695.00  1,672.10

In [9]:
NumCols = df.columns.drop(['Fecha'])
df[NumCols] = df[NumCols].replace({',': ''}, regex=True)
df[NumCols] = df[NumCols].astype('Float64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2583 entries, 0 to 2582
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Fecha     2583 non-null   datetime64[ns]
 1   Precio    2583 non-null   Float64
 2   Apertura  2583 non-null   Float64
 3   Máximo    2583 non-null   Float64
 4   Mínimo    2583 non-null   Float64
dtypes: Float64(4), datetime64[ns](1)
memory usage: 111.1 KB

In [10]:
df.head(2)

       Fecha  Precio  Apertura  Máximo  Mínimo
0 2013-01-02  1689.9    1675.8  1695.0  1672.1
1 2013-01-03  1675.6    1688.0  1689.3  1664.3

### Algoritmo de Separación

In [11]:
#Función de separación.
def particionar(df, porcentaje_entrenamiento, porcentaje_validacion, porcentaje_prueba):
    entradas = df[['Apertura', 'Máximo', 'Mínimo']]
    salidas = df['Precio']
    
    temp_size = porcentaje_validacion + porcentaje_prueba
    
    x_train, x_temp, y_train, y_temp = train_test_split(entradas, salidas, test_size=temp_size)
    
    if porcentaje_validacion > 0:
        test_size = porcentaje_prueba / temp_size
        x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size=test_size)
    else:
        return [x_train, None, x_temp, y_train, None, y_temp]
    
    return [x_train, x_val, x_test, y_train, y_val, y_test]

In [12]:
# Llamando a la función particionar para obtener los datos.
[x_train, x_val, x_test, y_train, y_val, y_test] = particionar(df,0.80,0.05,0.15)

print(x_train.shape)
print(x_val.shape)
print(x_test.shape)

(2066, 3)
(129, 3)
(388, 3)

In [13]:
#Funcion de separación de datasets con K-Fold (el usuario debe poner el k, si K =1 debe generar un Leave-One-Out Cross Validation).

def kFold(df, k, aleatorio, random_seed):
    indices_entrenamiento_prueba = []
    
    if k > 1:
        kfold = KFold(n_splits=k, shuffle=aleatorio, random_state=random_seed)
        ciclo = 1
        for indices_train, indices_test in kfold.split(df):
            indices_entrenamiento_prueba.append((indices_train, indices_test))
            print("Ciclo:", ciclo)
            print("Índices de entrenamiento:", indices_train)
            print("Índices de prueba:", indices_test)
            ciclo += 1
    elif k == 1:
        loocv = LeaveOneOut()
        ciclo = 1
        for train_index, test_index in loocv.split(df):
            indices_entrenamiento_prueba.append((train_index, test_index))
            print("Ciclo:", ciclo)
            print("Índices de entrenamiento:", train_index)
            
            print("Índices de prueba:", test_index)
            ciclo += 1
    else:
        print('K no puede ser menor a 1')
    
    return indices_entrenamiento_prueba

In [14]:
# Uso de la función kFold
kFold(df, 5, True, 42)

Ciclo: 1
Índices de entrenamiento: [   0    1    2 ... 2579 2580 2581]
Índices de prueba: [  25   29   30   43   44   48   49   51   56   57   67   69   70   73
   76   93   96  100  109  111  124  134  135  141  149  157  163  166
  168  170  173  175  178  179  188  194  196  199  208  210  211  212
  218  221  229  231  233  237  239  246  247  251  252  254  257  259
  261  279  282  289  291  296  298  315  318  321  322  324  332  347
  353  354  367  368  387  393  402  407  408  410  411  414  420  422
  430  432  433  435  436  438  440  443  445  450  457  461  463  464
  471  478  479  480  482  485  486  495  498  507  508  509  518  521
  522  527  528  530  532  544  554  564  565  567  568  572  582  596
  605  610  613  617  618  621  632  643  647  649  657  662  668  670
  680  693  695  705  727  742  746  748  755  756  761  764  765  781
  786  787  790  798  801  802  809  812  817  821  829  834  836  838
  839  861  867  869  873  879  881  888  889  890  900  902  903  907
  916  923  932  942  949  964  965  978  979  998 1000 1001 1014 1017
 1018 1025 1027 1029 1032 1033 1037 1041 1044 1047 1048 1053 1055 1056
 1058 1064 1071 1084 1090 1098 1100 1105 1106 1114 1127 1128 1133 1134
 1135 1137 1146 1151 1165 1177 1185 1186 1189 1190 1196 1199 1200 1207
 1208 1210 1213 1216 1220 1221 1223 1225 1226 1244 1253 1260 1264 1266
 1270 1273 1278 1283 1286 1289 1293 1295 1298 1302 1310 1316 1317 1322
 1333 1334 1336 1337 1344 1349 1350 1356 1361 1364 1366 1374 1375 1379
 1381 1385 1389 1391 1398 1411 1413 1420 1421 1425 1429 1435 1446 1448
 1457 1461 1463 1468 1474 1475 1477 1488 1491 1501 1502 1505 1509 1521
 1524 1525 1537 1546 1552 1558 1560 1561 1563 1565 1583 1593 1602 1606
 1607 1609 1610 1611 1613 1614 1621 1624 1632 1641 1642 1645 1652 1656
 1659 1662 1667 1672 1673 1674 1691 1712 1713 1714 1717 1720 1721 1725
 1729 1730 1740 1741 1742 1743 1746 1750 1755 1771 1788 1790 1793 1798
 1800 1804 1805 1807 1809 1815 1820 1829 1836 1846 1847 1851 1855 1867
 1871 1875 1879 1883 1894 1902 1905 1918 1920 1921 1929 1934 1940 1943
 1947 1953 1960 1963 1964 1965 1971 1983 1989 1991 1994 1995 1997 1999
 2004 2008 2010 2021 2032 2036 2040 2044 2055 2057 2058 2059 2063 2071
 2073 2075 2077 2080 2081 2087 2091 2096 2097 2099 2102 2104 2105 2108
 2112 2127 2128 2129 2138 2148 2154 2162 2164 2189 2190 2194 2195 2201
 2206 2210 2212 2218 2221 2222 2224 2233 2243 2258 2262 2279 2280 2288
 2291 2295 2297 2305 2310 2314 2315 2316 2329 2331 2332 2344 2349 2351
 2368 2373 2375 2376 2390 2392 2398 2412 2427 2428 2430 2439 2440 2445
 2447 2448 2456 2457 2464 2469 2490 2495 2496 2499 2505 2506 2513 2515
 2525 2528 2529 2534 2545 2547 2548 2549 2556 2564 2569 2578 2582]
Ciclo: 2
Índices de entrenamiento: [   0    1    2 ... 2579 2580 2582]
Índices de prueba: [   8   13   18   20   23   32   45   59   63   65   71   78   83   84
   87   99  105  115  118  120  121  123  128  151  152  158  162  174
  177  184  185  191  192  198  203  205  207  209  219  220  222  226
  230  240  256  263  266  270  272  273  275  277  278  281  283  286
  287  290  297  299  300  303  304  305  306  307  308  309  311  313
  316  331  340  342  343  344  350  351  358  360  361  365  366  374
  377  380  381  382  383  386  394  406  409  415  416  423  426  427
  429  439  444  458  462  472  483  489  491  494  497  500  506  511
  514  519  526  529  535  538  543  548  552  555  557  561  575  581
  583  590  591  598  599  601  602  604  607  611  620  629  630  636
  637  642  650  651  654  672  677  678  679  685  686  690  694  700
  707  715  719  729  733  736  741  744  759  767  772  782  785  788
  789  792  800  807  808  810  819  831  840  841  845  856  857  859
  862  866  874  883  885  886  891  906  911  912  915  926  927  929
  930  931  937  940  941  944  945  952  961  962  969  973  976  986
  988  990  999 1004 1005 1010 1011 1023 1034 1036 1050 1057 1061 1073
 1075 1078 1080 1089 1091 1093 1094 1097 1099 1102 1103 1113 1116 1117
 1123 1124 1125 1159 1163 1173 1174 1178 1187 1192 1193 1194 1195 1204
 1211 1229 1231 1236 1247 1251 1259 1261 1263 1271 1281 1285 1288 1290
 1292 1299 1313 1321 1325 1330 1338 1355 1357 1362 1368 1376 1377 1378
 1380 1387 1393 1403 1406 1407 1410 1412 1414 1418 1419 1422 1423 1432
 1441 1444 1449 1455 1456 1462 1465 1467 1476 1487 1494 1498 1499 1503
 1506 1510 1511 1512 1513 1514 1517 1535 1544 1547 1553 1554 1557 1564
 1572 1576 1591 1598 1601 1612 1615 1620 1623 1627 1637 1639 1647 1650
 1658 1660 1665 1666 1677 1684 1692 1697 1700 1701 1706 1708 1709 1710
 1711 1724 1728 1736 1744 1752 1760 1761 1765 1769 1772 1776 1784 1786
 1789 1791 1792 1828 1834 1835 1839 1840 1857 1864 1866 1869 1880 1885
 1896 1900 1908 1924 1925 1927 1932 1935 1936 1945 1948 1961 1962 1984
 1993 2000 2003 2007 2013 2017 2019 2025 2029 2031 2034 2035 2037 2042
 2048 2052 2064 2069 2079 2090 2092 2093 2103 2107 2110 2113 2114 2121
 2124 2125 2130 2132 2134 2136 2149 2158 2171 2172 2175 2178 2179 2184
 2187 2196 2204 2208 2209 2219 2230 2231 2236 2239 2241 2242 2251 2257
 2263 2265 2270 2271 2272 2273 2274 2281 2282 2283 2306 2319 2320 2322
 2326 2334 2337 2338 2342 2350 2354 2355 2359 2362 2365 2369 2370 2372
 2379 2386 2387 2389 2395 2401 2402 2404 2405 2408 2409 2410 2413 2414
 2446 2451 2455 2468 2470 2475 2480 2483 2489 2494 2500 2501 2509 2511
 2519 2524 2532 2538 2539 2540 2541 2550 2553 2555 2560 2574 2581]
Ciclo: 3
Índices de entrenamiento: [   0    1    3 ... 2579 2581 2582]
Índices de prueba: [   2    6   10   14   15   17   22   26   28   31   37   39   41   53
   54   58   61   72   81   86   91  101  107  113  126  129  136  140
  147  148  150  155  159  164  167  169  181  182  187  214  215  217
  236  243  244  250  265  271  274  285  292  294  310  312  323  326
  327  329  334  338  339  341  346  348  352  355  363  370  371  376
  385  398  405  413  425  428  431  441  442  447  451  453  454  465
  468  476  481  490  493  505  513  520  534  551  556  560  566  570
  571  576  579  584  585  588  589  592  593  609  614  619  626  628
  631  634  660  669  674  682  687  692  696  701  704  706  710  711
  712  720  721  722  726  730  734  743  745  752  754  757  768  771
  774  777  778  780  806  813  816  818  824  827  832  843  848  849
  855  865  871  875  887  892  893  904  905  909  913  914  921  925
  934  935  936  938  939  943  947  948  951  963  966  968  974  981
  982  984  985  987  993  994  997 1002 1003 1007 1009 1013 1022 1024
 1039 1040 1042 1043 1052 1054 1067 1068 1070 1072 1083 1085 1086 1087
 1104 1107 1109 1110 1111 1112 1121 1131 1132 1138 1143 1149 1157 1161
 1164 1170 1171 1175 1176 1179 1181 1198 1203 1222 1228 1232 1233 1234
 1237 1241 1242 1245 1249 1255 1258 1268 1269 1272 1279 1284 1287 1301
 1303 1304 1307 1308 1309 1311 1315 1320 1328 1332 1340 1341 1347 1351
 1352 1359 1360 1370 1382 1383 1386 1394 1395 1399 1401 1404 1405 1427
 1430 1436 1437 1447 1450 1451 1452 1453 1454 1459 1472 1480 1483 1486
 1490 1507 1508 1518 1530 1532 1533 1538 1539 1550 1551 1556 1559 1562
 1566 1567 1569 1575 1578 1580 1582 1584 1587 1590 1592 1594 1599 1600
 1608 1616 1618 1622 1626 1628 1640 1644 1651 1653 1655 1675 1688 1689
 1690 1694 1702 1716 1726 1731 1732 1735 1737 1739 1745 1749 1763 1766
 1767 1774 1777 1778 1779 1780 1801 1808 1811 1813 1814 1817 1822 1825
 1826 1830 1831 1832 1833 1844 1845 1849 1860 1861 1865 1870 1872 1876
 1882 1888 1889 1904 1907 1910 1911 1912 1915 1917 1922 1937 1942 1956
 1957 1967 1968 1970 1972 1973 1977 1978 1979 1980 1985 1988 2005 2009
 2011 2014 2018 2022 2023 2024 2030 2033 2043 2045 2046 2051 2054 2060
 2078 2084 2089 2095 2098 2100 2111 2115 2117 2120 2122 2123 2144 2147
 2151 2155 2156 2157 2159 2161 2167 2168 2174 2180 2186 2207 2223 2225
 2250 2254 2268 2269 2284 2285 2286 2287 2289 2290 2293 2296 2298 2303
 2307 2312 2313 2321 2323 2335 2340 2347 2348 2353 2356 2371 2378 2380
 2381 2388 2403 2406 2407 2415 2419 2420 2422 2423 2426 2432 2436 2437
 2442 2450 2453 2460 2461 2474 2479 2485 2486 2487 2492 2493 2498 2503
 2504 2521 2522 2523 2536 2554 2557 2566 2567 2571 2576 2577 2580]
Ciclo: 4
Índices de entrenamiento: [   1    2    4 ... 2580 2581 2582]
Índices de prueba: [   0    3    5    7    9   12   24   27   33   40   42   47   52   55
   60   62   66   68   74   77   79   80   82   85   88   92   94   97
  102  104  106  108  110  112  117  125  131  132  133  137  138  139
  142  144  145  156  165  171  176  183  193  195  204  213  223  224
  227  228  232  235  238  242  248  249  255  258  260  267  269  276
  280  288  295  302  314  319  320  325  328  333  336  345  349  357
  359  362  364  372  373  375  384  388  389  390  401  404  419  421
  424  434  437  446  448  449  456  460  467  470  473  475  477  484
  501  503  516  517  523  525  531  533  536  539  541  542  545  547
  549  553  558  573  577  578  587  594  597  603  612  615  622  624
  638  644  645  653  655  661  664  665  666  667  671  673  676  688
  689  691  697  708  714  716  718  723  724  725  731  735  737  738
  739  749  751  758  760  762  770  776  783  793  794  796  799  803
  805  811  814  820  822  826  842  844  846  847  852  858  864  868
  882  897  898  899  901  908  910  917  918  919  922  924  928  933
  946  950  958  967  970  983  989 1006 1019 1026 1030 1031 1035 1046
 1049 1063 1074 1079 1088 1096 1101 1108 1118 1120 1140 1142 1144 1145
 1160 1168 1169 1172 1182 1188 1201 1202 1206 1224 1230 1235 1239 1240
 1246 1248 1250 1252 1254 1256 1262 1265 1274 1276 1277 1280 1305 1314
 1318 1319 1323 1326 1329 1331 1335 1339 1342 1343 1345 1353 1358 1371
 1372 1373 1392 1396 1397 1402 1417 1424 1426 1428 1431 1433 1442 1458
 1460 1464 1466 1469 1471 1473 1481 1489 1493 1497 1523 1526 1536 1541
 1543 1545 1549 1555 1573 1574 1577 1581 1586 1588 1596 1604 1605 1617
 1619 1629 1633 1646 1654 1657 1668 1669 1670 1671 1681 1699 1703 1718
 1719 1723 1727 1738 1747 1748 1753 1754 1756 1762 1764 1770 1775 1783
 1795 1797 1803 1812 1818 1824 1837 1838 1842 1848 1850 1852 1854 1858
 1859 1862 1868 1873 1874 1877 1878 1886 1887 1891 1893 1897 1898 1901
 1909 1913 1914 1916 1926 1928 1933 1938 1939 1941 1944 1946 1949 1950
 1951 1952 1954 1966 1975 1976 1987 1990 1992 2001 2002 2012 2015 2016
 2020 2026 2028 2039 2050 2053 2066 2067 2072 2083 2086 2094 2106 2116
 2118 2119 2126 2133 2137 2140 2142 2145 2150 2152 2163 2166 2173 2176
 2181 2183 2185 2188 2192 2203 2211 2213 2215 2226 2229 2232 2234 2238
 2240 2244 2245 2246 2247 2248 2249 2252 2256 2259 2260 2261 2266 2275
 2276 2292 2299 2304 2309 2311 2325 2328 2333 2345 2352 2358 2361 2364
 2366 2367 2374 2377 2382 2383 2385 2393 2394 2396 2399 2400 2411 2425
 2429 2431 2434 2438 2458 2462 2465 2467 2472 2473 2476 2484 2502 2507
 2508 2518 2531 2542 2544 2546 2558 2559 2563 2570 2573 2579]
Ciclo: 5
Índices de entrenamiento: [   0    2    3 ... 2580 2581 2582]
Índices de prueba: [   1    4   11   16   19   21   34   35   36   38   46   50   64   75
   89   90   95   98  103  114  116  119  122  127  130  143  146  153
  154  160  161  172  180  186  189  190  197  200  201  202  206  216
  225  234  241  245  253  262  264  268  284  293  301  317  330  335
  337  356  369  378  379  391  392  395  396  397  399  400  403  412
  417  418  452  455  459  466  469  474  487  488  492  496  499  502
  504  510  512  515  524  537  540  546  550  559  562  563  569  574
  580  586  595  600  606  608  616  623  625  627  633  635  639  640
  641  646  648  652  656  658  659  663  675  681  683  684  698  699
  702  703  709  713  717  728  732  740  747  750  753  763  766  769
  773  775  779  784  791  795  797  804  815  823  825  828  830  833
  835  837  850  851  853  854  860  863  870  872  876  877  878  880
  884  894  895  896  920  953  954  955  956  957  959  960  971  972
  975  977  980  991  992  995  996 1008 1012 1015 1016 1020 1021 1028
 1038 1045 1051 1059 1060 1062 1065 1066 1069 1076 1077 1081 1082 1092
 1095 1115 1119 1122 1126 1129 1130 1136 1139 1141 1147 1148 1150 1152
 1153 1154 1155 1156 1158 1162 1166 1167 1180 1183 1184 1191 1197 1205
 1209 1212 1214 1215 1217 1218 1219 1227 1238 1243 1257 1267 1275 1282
 1291 1294 1296 1297 1300 1306 1312 1324 1327 1346 1348 1354 1363 1365
 1367 1369 1384 1388 1390 1400 1408 1409 1415 1416 1434 1438 1439 1440
 1443 1445 1470 1478 1479 1482 1484 1485 1492 1495 1496 1500 1504 1515
 1516 1519 1520 1522 1527 1528 1529 1531 1534 1540 1542 1548 1568 1570
 1571 1579 1585 1589 1595 1597 1603 1625 1630 1631 1634 1635 1636 1638
 1643 1648 1649 1661 1663 1664 1676 1678 1679 1680 1682 1683 1685 1686
 1687 1693 1695 1696 1698 1704 1705 1707 1715 1722 1733 1734 1751 1757
 1758 1759 1768 1773 1781 1782 1785 1787 1794 1796 1799 1802 1806 1810
 1816 1819 1821 1823 1827 1841 1843 1853 1856 1863 1881 1884 1890 1892
 1895 1899 1903 1906 1919 1923 1930 1931 1955 1958 1959 1969 1974 1981
 1982 1986 1996 1998 2006 2027 2038 2041 2047 2049 2056 2061 2062 2065
 2068 2070 2074 2076 2082 2085 2088 2101 2109 2131 2135 2139 2141 2143
 2146 2153 2160 2165 2169 2170 2177 2182 2191 2193 2197 2198 2199 2200
 2202 2205 2214 2216 2217 2220 2227 2228 2235 2237 2253 2255 2264 2267
 2277 2278 2294 2300 2301 2302 2308 2317 2318 2324 2327 2330 2336 2339
 2341 2343 2346 2357 2360 2363 2384 2391 2397 2416 2417 2418 2421 2424
 2433 2435 2441 2443 2444 2449 2452 2454 2459 2463 2466 2471 2477 2478
 2481 2482 2488 2491 2497 2510 2512 2514 2516 2517 2520 2526 2527 2530
 2533 2535 2537 2543 2551 2552 2561 2562 2565 2568 2572 2575]

[(array([   0,    1,    2, ..., 2579, 2580, 2581]),
  array([  25,   29,   30,   43,   44,   48,   49,   51,   56,   57,   67,
           69,   70,   73,   76,   93,   96,  100,  109,  111,  124,  134,
          135,  141,  149,  157,  163,  166,  168,  170,  173,  175,  178,
          179,  188,  194,  196,  199,  208,  210,  211,  212,  218,  221,
          229,  231,  233,  237,  239,  246,  247,  251,  252,  254,  257,
          259,  261,  279,  282,  289,  291,  296,  298,  315,  318,  321,
          322,  324,  332,  347,  353,  354,  367,  368,  387,  393,  402,
          407,  408,  410,  411,  414,  420,  422,  430,  432,  433,  435,
          436,  438,  440,  443,  445,  450,  457,  461,  463,  464,  471,
          478,  479,  480,  482,  485,  486,  495,  498,  507,  508,  509,
          518,  521,  522,  527,  528,  530,  532,  544,  554,  564,  565,
          567,  568,  572,  582,  596,  605,  610,  613,  617,  618,  621,
          632,  643,  647,  649,  657,  662,  668,  670,  680,  693,  695,
          705,  727,  742,  746,  748,  755,  756,  761,  764,  765,  781,
          786,  787,  790,  798,  801,  802,  809,  812,  817,  821,  829,
          834,  836,  838,  839,  861,  867,  869,  873,  879,  881,  888,
          889,  890,  900,  902,  903,  907,  916,  923,  932,  942,  949,
          964,  965,  978,  979,  998, 1000, 1001, 1014, 1017, 1018, 1025,
         1027, 1029, 1032, 1033, 1037, 1041, 1044, 1047, 1048, 1053, 1055,
         1056, 1058, 1064, 1071, 1084, 1090, 1098, 1100, 1105, 1106, 1114,
         1127, 1128, 1133, 1134, 1135, 1137, 1146, 1151, 1165, 1177, 1185,
         1186, 1189, 1190, 1196, 1199, 1200, 1207, 1208, 1210, 1213, 1216,
         1220, 1221, 1223, 1225, 1226, 1244, 1253, 1260, 1264, 1266, 1270,
         1273, 1278, 1283, 1286, 1289, 1293, 1295, 1298, 1302, 1310, 1316,
         1317, 1322, 1333, 1334, 1336, 1337, 1344, 1349, 1350, 1356, 1361,
         1364, 1366, 1374, 1375, 1379, 1381, 1385, 1389, 1391, 1398, 1411,
         1413, 1420, 1421, 1425, 1429, 1435, 1446, 1448, 1457, 1461, 1463,
         1468, 1474, 1475, 1477, 1488, 1491, 1501, 1502, 1505, 1509, 1521,
         1524, 1525, 1537, 1546, 1552, 1558, 1560, 1561, 1563, 1565, 1583,
         1593, 1602, 1606, 1607, 1609, 1610, 1611, 1613, 1614, 1621, 1624,
         1632, 1641, 1642, 1645, 1652, 1656, 1659, 1662, 1667, 1672, 1673,
         1674, 1691, 1712, 1713, 1714, 1717, 1720, 1721, 1725, 1729, 1730,
         1740, 1741, 1742, 1743, 1746, 1750, 1755, 1771, 1788, 1790, 1793,
         1798, 1800, 1804, 1805, 1807, 1809, 1815, 1820, 1829, 1836, 1846,
         1847, 1851, 1855, 1867, 1871, 1875, 1879, 1883, 1894, 1902, 1905,
         1918, 1920, 1921, 1929, 1934, 1940, 1943, 1947, 1953, 1960, 1963,
         1964, 1965, 1971, 1983, 1989, 1991, 1994, 1995, 1997, 1999, 2004,
         2008, 2010, 2021, 2032, 2036, 2040, 2044, 2055, 2057, 2058, 2059,
         2063, 2071, 2073, 2075, 2077, 2080, 2081, 2087, 2091, 2096, 2097,
         2099, 2102, 2104, 2105, 2108, 2112, 2127, 2128, 2129, 2138, 2148,
         2154, 2162, 2164, 2189, 2190, 2194, 2195, 2201, 2206, 2210, 2212,
         2218, 2221, 2222, 2224, 2233, 2243, 2258, 2262, 2279, 2280, 2288,
         2291, 2295, 2297, 2305, 2310, 2314, 2315, 2316, 2329, 2331, 2332,
         2344, 2349, 2351, 2368, 2373, 2375, 2376, 2390, 2392, 2398, 2412,
         2427, 2428, 2430, 2439, 2440, 2445, 2447, 2448, 2456, 2457, 2464,
         2469, 2490, 2495, 2496, 2499, 2505, 2506, 2513, 2515, 2525, 2528,
         2529, 2534, 2545, 2547, 2548, 2549, 2556, 2564, 2569, 2578, 2582])),
 (array([   0,    1,    2, ..., 2579, 2580, 2582]),
  array([   8,   13,   18,   20,   23,   32,   45,   59,   63,   65,   71,
           78,   83,   84,   87,   99,  105,  115,  118,  120,  121,  123,
          128,  151,  152,  158,  162,  174,  177,  184,  185,  191,  192,
          198,  203,  205,  207,  209,  219,  220,  222,  226,  230,  240,
          256,  263,  266,  270,  272,  273,  275,  277,  278,  281,  283,
          286,  287,  290,  297,  299,  300,  303,  304,  305,  306,  307,
          308,  309,  311,  313,  316,  331,  340,  342,  343,  344,  350,
          351,  358,  360,  361,  365,  366,  374,  377,  380,  381,  382,
          383,  386,  394,  406,  409,  415,  416,  423,  426,  427,  429,
          439,  444,  458,  462,  472,  483,  489,  491,  494,  497,  500,
          506,  511,  514,  519,  526,  529,  535,  538,  543,  548,  552,
          555,  557,  561,  575,  581,  583,  590,  591,  598,  599,  601,
          602,  604,  607,  611,  620,  629,  630,  636,  637,  642,  650,
          651,  654,  672,  677,  678,  679,  685,  686,  690,  694,  700,
          707,  715,  719,  729,  733,  736,  741,  744,  759,  767,  772,
          782,  785,  788,  789,  792,  800,  807,  808,  810,  819,  831,
          840,  841,  845,  856,  857,  859,  862,  866,  874,  883,  885,
          886,  891,  906,  911,  912,  915,  926,  927,  929,  930,  931,
          937,  940,  941,  944,  945,  952,  961,  962,  969,  973,  976,
          986,  988,  990,  999, 1004, 1005, 1010, 1011, 1023, 1034, 1036,
         1050, 1057, 1061, 1073, 1075, 1078, 1080, 1089, 1091, 1093, 1094,
         1097, 1099, 1102, 1103, 1113, 1116, 1117, 1123, 1124, 1125, 1159,
         1163, 1173, 1174, 1178, 1187, 1192, 1193, 1194, 1195, 1204, 1211,
         1229, 1231, 1236, 1247, 1251, 1259, 1261, 1263, 1271, 1281, 1285,
         1288, 1290, 1292, 1299, 1313, 1321, 1325, 1330, 1338, 1355, 1357,
         1362, 1368, 1376, 1377, 1378, 1380, 1387, 1393, 1403, 1406, 1407,
         1410, 1412, 1414, 1418, 1419, 1422, 1423, 1432, 1441, 1444, 1449,
         1455, 1456, 1462, 1465, 1467, 1476, 1487, 1494, 1498, 1499, 1503,
         1506, 1510, 1511, 1512, 1513, 1514, 1517, 1535, 1544, 1547, 1553,
         1554, 1557, 1564, 1572, 1576, 1591, 1598, 1601, 1612, 1615, 1620,
         1623, 1627, 1637, 1639, 1647, 1650, 1658, 1660, 1665, 1666, 1677,
         1684, 1692, 1697, 1700, 1701, 1706, 1708, 1709, 1710, 1711, 1724,
         1728, 1736, 1744, 1752, 1760, 1761, 1765, 1769, 1772, 1776, 1784,
         1786, 1789, 1791, 1792, 1828, 1834, 1835, 1839, 1840, 1857, 1864,
         1866, 1869, 1880, 1885, 1896, 1900, 1908, 1924, 1925, 1927, 1932,
         1935, 1936, 1945, 1948, 1961, 1962, 1984, 1993, 2000, 2003, 2007,
         2013, 2017, 2019, 2025, 2029, 2031, 2034, 2035, 2037, 2042, 2048,
         2052, 2064, 2069, 2079, 2090, 2092, 2093, 2103, 2107, 2110, 2113,
         2114, 2121, 2124, 2125, 2130, 2132, 2134, 2136, 2149, 2158, 2171,
         2172, 2175, 2178, 2179, 2184, 2187, 2196, 2204, 2208, 2209, 2219,
         2230, 2231, 2236, 2239, 2241, 2242, 2251, 2257, 2263, 2265, 2270,
         2271, 2272, 2273, 2274, 2281, 2282, 2283, 2306, 2319, 2320, 2322,
         2326, 2334, 2337, 2338, 2342, 2350, 2354, 2355, 2359, 2362, 2365,
         2369, 2370, 2372, 2379, 2386, 2387, 2389, 2395, 2401, 2402, 2404,
         2405, 2408, 2409, 2410, 2413, 2414, 2446, 2451, 2455, 2468, 2470,
         2475, 2480, 2483, 2489, 2494, 2500, 2501, 2509, 2511, 2519, 2524,
         2532, 2538, 2539, 2540, 2541, 2550, 2553, 2555, 2560, 2574, 2581])),
 (array([   0,    1,    3, ..., 2579, 2581, 2582]),
  array([   2,    6,   10,   14,   15,   17,   22,   26,   28,   31,   37,
           39,   41,   53,   54,   58,   61,   72,   81,   86,   91,  101,
          107,  113,  126,  129,  136,  140,  147,  148,  150,  155,  159,
          164,  167,  169,  181,  182,  187,  214,  215,  217,  236,  243,
          244,  250,  265,  271,  274,  285,  292,  294,  310,  312,  323,
          326,  327,  329,  334,  338,  339,  341,  346,  348,  352,  355,
          363,  370,  371,  376,  385,  398,  405,  413,  425,  428,  431,
          441,  442,  447,  451,  453,  454,  465,  468,  476,  481,  490,
          493,  505,  513,  520,  534,  551,  556,  560,  566,  570,  571,
          576,  579,  584,  585,  588,  589,  592,  593,  609,  614,  619,
          626,  628,  631,  634,  660,  669,  674,  682,  687,  692,  696,
          701,  704,  706,  710,  711,  712,  720,  721,  722,  726,  730,
          734,  743,  745,  752,  754,  757,  768,  771,  774,  777,  778,
          780,  806,  813,  816,  818,  824,  827,  832,  843,  848,  849,
          855,  865,  871,  875,  887,  892,  893,  904,  905,  909,  913,
          914,  921,  925,  934,  935,  936,  938,  939,  943,  947,  948,
          951,  963,  966,  968,  974,  981,  982,  984,  985,  987,  993,
          994,  997, 1002, 1003, 1007, 1009, 1013, 1022, 1024, 1039, 1040,
         1042, 1043, 1052, 1054, 1067, 1068, 1070, 1072, 1083, 1085, 1086,
         1087, 1104, 1107, 1109, 1110, 1111, 1112, 1121, 1131, 1132, 1138,
         1143, 1149, 1157, 1161, 1164, 1170, 1171, 1175, 1176, 1179, 1181,
         1198, 1203, 1222, 1228, 1232, 1233, 1234, 1237, 1241, 1242, 1245,
         1249, 1255, 1258, 1268, 1269, 1272, 1279, 1284, 1287, 1301, 1303,
         1304, 1307, 1308, 1309, 1311, 1315, 1320, 1328, 1332, 1340, 1341,
         1347, 1351, 1352, 1359, 1360, 1370, 1382, 1383, 1386, 1394, 1395,
         1399, 1401, 1404, 1405, 1427, 1430, 1436, 1437, 1447, 1450, 1451,
         1452, 1453, 1454, 1459, 1472, 1480, 1483, 1486, 1490, 1507, 1508,
         1518, 1530, 1532, 1533, 1538, 1539, 1550, 1551, 1556, 1559, 1562,
         1566, 1567, 1569, 1575, 1578, 1580, 1582, 1584, 1587, 1590, 1592,
         1594, 1599, 1600, 1608, 1616, 1618, 1622, 1626, 1628, 1640, 1644,
         1651, 1653, 1655, 1675, 1688, 1689, 1690, 1694, 1702, 1716, 1726,
         1731, 1732, 1735, 1737, 1739, 1745, 1749, 1763, 1766, 1767, 1774,
         1777, 1778, 1779, 1780, 1801, 1808, 1811, 1813, 1814, 1817, 1822,
         1825, 1826, 1830, 1831, 1832, 1833, 1844, 1845, 1849, 1860, 1861,
         1865, 1870, 1872, 1876, 1882, 1888, 1889, 1904, 1907, 1910, 1911,
         1912, 1915, 1917, 1922, 1937, 1942, 1956, 1957, 1967, 1968, 1970,
         1972, 1973, 1977, 1978, 1979, 1980, 1985, 1988, 2005, 2009, 2011,
         2014, 2018, 2022, 2023, 2024, 2030, 2033, 2043, 2045, 2046, 2051,
         2054, 2060, 2078, 2084, 2089, 2095, 2098, 2100, 2111, 2115, 2117,
         2120, 2122, 2123, 2144, 2147, 2151, 2155, 2156, 2157, 2159, 2161,
         2167, 2168, 2174, 2180, 2186, 2207, 2223, 2225, 2250, 2254, 2268,
         2269, 2284, 2285, 2286, 2287, 2289, 2290, 2293, 2296, 2298, 2303,
         2307, 2312, 2313, 2321, 2323, 2335, 2340, 2347, 2348, 2353, 2356,
         2371, 2378, 2380, 2381, 2388, 2403, 2406, 2407, 2415, 2419, 2420,
         2422, 2423, 2426, 2432, 2436, 2437, 2442, 2450, 2453, 2460, 2461,
         2474, 2479, 2485, 2486, 2487, 2492, 2493, 2498, 2503, 2504, 2521,
         2522, 2523, 2536, 2554, 2557, 2566, 2567, 2571, 2576, 2577, 2580])),
 (array([   1,    2,    4, ..., 2580, 2581, 2582]),
  array([   0,    3,    5,    7,    9,   12,   24,   27,   33,   40,   42,
           47,   52,   55,   60,   62,   66,   68,   74,   77,   79,   80,
           82,   85,   88,   92,   94,   97,  102,  104,  106,  108,  110,
          112,  117,  125,  131,  132,  133,  137,  138,  139,  142,  144,
          145,  156,  165,  171,  176,  183,  193,  195,  204,  213,  223,
          224,  227,  228,  232,  235,  238,  242,  248,  249,  255,  258,
          260,  267,  269,  276,  280,  288,  295,  302,  314,  319,  320,
          325,  328,  333,  336,  345,  349,  357,  359,  362,  364,  372,
          373,  375,  384,  388,  389,  390,  401,  404,  419,  421,  424,
          434,  437,  446,  448,  449,  456,  460,  467,  470,  473,  475,
          477,  484,  501,  503,  516,  517,  523,  525,  531,  533,  536,
          539,  541,  542,  545,  547,  549,  553,  558,  573,  577,  578,
          587,  594,  597,  603,  612,  615,  622,  624,  638,  644,  645,
          653,  655,  661,  664,  665,  666,  667,  671,  673,  676,  688,
          689,  691,  697,  708,  714,  716,  718,  723,  724,  725,  731,
          735,  737,  738,  739,  749,  751,  758,  760,  762,  770,  776,
          783,  793,  794,  796,  799,  803,  805,  811,  814,  820,  822,
          826,  842,  844,  846,  847,  852,  858,  864,  868,  882,  897,
          898,  899,  901,  908,  910,  917,  918,  919,  922,  924,  928,
          933,  946,  950,  958,  967,  970,  983,  989, 1006, 1019, 1026,
         1030, 1031, 1035, 1046, 1049, 1063, 1074, 1079, 1088, 1096, 1101,
         1108, 1118, 1120, 1140, 1142, 1144, 1145, 1160, 1168, 1169, 1172,
         1182, 1188, 1201, 1202, 1206, 1224, 1230, 1235, 1239, 1240, 1246,
         1248, 1250, 1252, 1254, 1256, 1262, 1265, 1274, 1276, 1277, 1280,
         1305, 1314, 1318, 1319, 1323, 1326, 1329, 1331, 1335, 1339, 1342,
         1343, 1345, 1353, 1358, 1371, 1372, 1373, 1392, 1396, 1397, 1402,
         1417, 1424, 1426, 1428, 1431, 1433, 1442, 1458, 1460, 1464, 1466,
         1469, 1471, 1473, 1481, 1489, 1493, 1497, 1523, 1526, 1536, 1541,
         1543, 1545, 1549, 1555, 1573, 1574, 1577, 1581, 1586, 1588, 1596,
         1604, 1605, 1617, 1619, 1629, 1633, 1646, 1654, 1657, 1668, 1669,
         1670, 1671, 1681, 1699, 1703, 1718, 1719, 1723, 1727, 1738, 1747,
         1748, 1753, 1754, 1756, 1762, 1764, 1770, 1775, 1783, 1795, 1797,
         1803, 1812, 1818, 1824, 1837, 1838, 1842, 1848, 1850, 1852, 1854,
         1858, 1859, 1862, 1868, 1873, 1874, 1877, 1878, 1886, 1887, 1891,
         1893, 1897, 1898, 1901, 1909, 1913, 1914, 1916, 1926, 1928, 1933,
         1938, 1939, 1941, 1944, 1946, 1949, 1950, 1951, 1952, 1954, 1966,
         1975, 1976, 1987, 1990, 1992, 2001, 2002, 2012, 2015, 2016, 2020,
         2026, 2028, 2039, 2050, 2053, 2066, 2067, 2072, 2083, 2086, 2094,
         2106, 2116, 2118, 2119, 2126, 2133, 2137, 2140, 2142, 2145, 2150,
         2152, 2163, 2166, 2173, 2176, 2181, 2183, 2185, 2188, 2192, 2203,
         2211, 2213, 2215, 2226, 2229, 2232, 2234, 2238, 2240, 2244, 2245,
         2246, 2247, 2248, 2249, 2252, 2256, 2259, 2260, 2261, 2266, 2275,
         2276, 2292, 2299, 2304, 2309, 2311, 2325, 2328, 2333, 2345, 2352,
         2358, 2361, 2364, 2366, 2367, 2374, 2377, 2382, 2383, 2385, 2393,
         2394, 2396, 2399, 2400, 2411, 2425, 2429, 2431, 2434, 2438, 2458,
         2462, 2465, 2467, 2472, 2473, 2476, 2484, 2502, 2507, 2508, 2518,
         2531, 2542, 2544, 2546, 2558, 2559, 2563, 2570, 2573, 2579])),
 (array([   0,    2,    3, ..., 2580, 2581, 2582]),
  array([   1,    4,   11,   16,   19,   21,   34,   35,   36,   38,   46,
           50,   64,   75,   89,   90,   95,   98,  103,  114,  116,  119,
          122,  127,  130,  143,  146,  153,  154,  160,  161,  172,  180,
          186,  189,  190,  197,  200,  201,  202,  206,  216,  225,  234,
          241,  245,  253,  262,  264,  268,  284,  293,  301,  317,  330,
          335,  337,  356,  369,  378,  379,  391,  392,  395,  396,  397,
          399,  400,  403,  412,  417,  418,  452,  455,  459,  466,  469,
          474,  487,  488,  492,  496,  499,  502,  504,  510,  512,  515,
          524,  537,  540,  546,  550,  559,  562,  563,  569,  574,  580,
          586,  595,  600,  606,  608,  616,  623,  625,  627,  633,  635,
          639,  640,  641,  646,  648,  652,  656,  658,  659,  663,  675,
          681,  683,  684,  698,  699,  702,  703,  709,  713,  717,  728,
          732,  740,  747,  750,  753,  763,  766,  769,  773,  775,  779,
          784,  791,  795,  797,  804,  815,  823,  825,  828,  830,  833,
          835,  837,  850,  851,  853,  854,  860,  863,  870,  872,  876,
          877,  878,  880,  884,  894,  895,  896,  920,  953,  954,  955,
          956,  957,  959,  960,  971,  972,  975,  977,  980,  991,  992,
          995,  996, 1008, 1012, 1015, 1016, 1020, 1021, 1028, 1038, 1045,
         1051, 1059, 1060, 1062, 1065, 1066, 1069, 1076, 1077, 1081, 1082,
         1092, 1095, 1115, 1119, 1122, 1126, 1129, 1130, 1136, 1139, 1141,
         1147, 1148, 1150, 1152, 1153, 1154, 1155, 1156, 1158, 1162, 1166,
         1167, 1180, 1183, 1184, 1191, 1197, 1205, 1209, 1212, 1214, 1215,
         1217, 1218, 1219, 1227, 1238, 1243, 1257, 1267, 1275, 1282, 1291,
         1294, 1296, 1297, 1300, 1306, 1312, 1324, 1327, 1346, 1348, 1354,
         1363, 1365, 1367, 1369, 1384, 1388, 1390, 1400, 1408, 1409, 1415,
         1416, 1434, 1438, 1439, 1440, 1443, 1445, 1470, 1478, 1479, 1482,
         1484, 1485, 1492, 1495, 1496, 1500, 1504, 1515, 1516, 1519, 1520,
         1522, 1527, 1528, 1529, 1531, 1534, 1540, 1542, 1548, 1568, 1570,
         1571, 1579, 1585, 1589, 1595, 1597, 1603, 1625, 1630, 1631, 1634,
         1635, 1636, 1638, 1643, 1648, 1649, 1661, 1663, 1664, 1676, 1678,
         1679, 1680, 1682, 1683, 1685, 1686, 1687, 1693, 1695, 1696, 1698,
         1704, 1705, 1707, 1715, 1722, 1733, 1734, 1751, 1757, 1758, 1759,
         1768, 1773, 1781, 1782, 1785, 1787, 1794, 1796, 1799, 1802, 1806,
         1810, 1816, 1819, 1821, 1823, 1827, 1841, 1843, 1853, 1856, 1863,
         1881, 1884, 1890, 1892, 1895, 1899, 1903, 1906, 1919, 1923, 1930,
         1931, 1955, 1958, 1959, 1969, 1974, 1981, 1982, 1986, 1996, 1998,
         2006, 2027, 2038, 2041, 2047, 2049, 2056, 2061, 2062, 2065, 2068,
         2070, 2074, 2076, 2082, 2085, 2088, 2101, 2109, 2131, 2135, 2139,
         2141, 2143, 2146, 2153, 2160, 2165, 2169, 2170, 2177, 2182, 2191,
         2193, 2197, 2198, 2199, 2200, 2202, 2205, 2214, 2216, 2217, 2220,
         2227, 2228, 2235, 2237, 2253, 2255, 2264, 2267, 2277, 2278, 2294,
         2300, 2301, 2302, 2308, 2317, 2318, 2324, 2327, 2330, 2336, 2339,
         2341, 2343, 2346, 2357, 2360, 2363, 2384, 2391, 2397, 2416, 2417,
         2418, 2421, 2424, 2433, 2435, 2441, 2443, 2444, 2449, 2452, 2454,
         2459, 2463, 2466, 2471, 2477, 2478, 2481, 2482, 2488, 2491, 2497,
         2510, 2512, 2514, 2516, 2517, 2520, 2526, 2527, 2530, 2533, 2535,
         2537, 2543, 2551, 2552, 2561, 2562, 2565, 2568, 2572, 2575]))]

In [15]:
# Función de la matriz de confusion
def matriz_confusion(valor_real, prediccion):
    y_esperados = np.array(valor_real)
    y_predichos = np.array(prediccion)
    resultado = confusion_matrix(valor_real, prediccion)
    print(resultado)
    (TN, FP, FN, TP) = resultado.ravel()
    print("\nTrue positives: "+str(TP))
    print("True negatives: "+str(TN))
    print("False positives: "+str(FP))
    print("False negative: "+str(FN))
    return (TP, TN, FP, FN)

In [16]:
def calcularAccuracy(TP, TN, FP, FN):
    accuracy = ((TP + TN) / (TP + TN + FP + FN)) * 100
    return accuracy

def calcularSensibilidad(TP, TN, FP, FN):
    sensibilidad = (TP / (TP + FN)) * 100
    return sensibilidad

def calcularEspecificidad(TP, TN, FP, FN):
    especificidad = (TN / (TN + FP)) * 100
    return especificidad

### Algoritmo No Supervisado (keans)

In [17]:
# Funciones para el Algoritmo

In [18]:
def distEuclidiana(muestra, dataset):
    distancias = np.zeros((dataset.shape[0],1))
    for counter in range(0,dataset.shape[0]):
        distancias[counter] = np.linalg.norm(muestra-dataset[counter])
    return distancias

def centroideCercano(muestra, listaCentroides):
    listaDistancias = distEuclidiana(muestra, listaCentroides)
    centroideCercano = np.argmin(listaDistancias)
    return centroideCercano

def clasificarPorCentroides(muestras, centroides):
    resultado = np.zeros((muestras.shape[0],1))
    for counter in range(0, muestras.shape[0]):
        resultado[counter] = centroideCercano(muestras[counter], centroides)
    return resultado

def separarDatos(muestras, valoresEsperados, valorAFiltrar):
    indices = np.where(valoresEsperados == valorAFiltrar)
    return muestras[indices], valoresEsperados[indices]

def obtenerModa(resultados):
    moda = (stats.mode(resultados)[0]).reshape(-1)
    return moda[0]

def obtenerAccuracy_kmedias(muestras, centroides):
    numMuestras = muestras.shape[0]
    resultados = clasificarPorCentroides(muestras, centroides)
    moda = obtenerModa(resultados)
    indicesErrores = np.where(resultados != moda)
    cantidadErrores = len(resultados[indicesErrores])
    accuracy = ((numMuestras - cantidadErrores) / numMuestras) *100
    return accuracy

### Preparación de del DataSet

In [19]:
# Recomendación de canciones
df_canciones = pd.read_csv('data.csv')
df_canciones.head(3)

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339

In [20]:
column_name_canciones = {
    'release_date': 'Fecha de lanzamiento',
    'valence': 'Valencia',
    'acousticness': 'Acústica',
    'artists': 'Artistas',
    'danceability': 'Bailable',
    'duration_ms': 'Duración en milisegundos',
    'energy': 'Energía',
    'explicit': 'Explícito',
    'id': 'ID',
    'instrumentalness': 'Instrumentalidad',
    'key': 'Tonalidad',
    'liveness': 'Vivacidad',
    'loudness': 'Sonoridad',
    'mode': 'Modo',
    'name': 'Nombre',
    'popularity': 'Popularidad',
    'release_date': 'Fecha de lanzamiento',
    'speechiness': 'Hablada',
    'tempo': 'Tempo'
}
df_canciones = df_canciones.rename(columns = column_name_canciones)

df_canciones.head(3)

,Valencia,year,Acústica,Artistas,Bailable,Duración en milisegundos,Energía,Explícito,ID,Instrumentalidad,Tonalidad,Vivacidad,Sonoridad,Modo,Nombre,Popularidad,Fecha de lanzamiento,Hablada,Tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339

In [21]:
columnas = ['Valencia', 'Acústica', 'Bailable', 'Energía', 'Instrumentalidad', 'Vivacidad', 'Hablada']
df_canciones[columnas] = df_canciones[columnas].round()
df_canciones.head(4)

,Valencia,year,Acústica,Artistas,Bailable,Duración en milisegundos,Energía,Explícito,ID,Instrumentalidad,Tonalidad,Vivacidad,Sonoridad,Modo,Nombre,Popularidad,Fecha de lanzamiento,Hablada,Tempo
0,0.0,1921,1.0,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.0,831667,0.0,0,4BJqT0PrAfrxzMOxytFOIz,1.0,10,1.0,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0,80.954
1,1.0,1921,1.0,['Dennis Day'],1.0,180533,0.0,0,7xPhfUan2yNtyFG0cUWkt8,0.0,7,0.0,-12.441,1,Clancy Lowered the Boom,5,1921,0.0,60.936
2,0.0,1921,1.0,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.0,500062,0.0,0,1o6I8BglA6ylDMrIELygv1,1.0,3,0.0,-14.850,1,Gati Bali,5,1921,0.0,110.339
3,0.0,1921,1.0,['Frank Parker'],0.0,210000,0.0,0,3ftBPsC5vPBKxYSee08FDH,0.0,5,0.0,-9.316,1,Danny Boy,3,1921,0.0,100.109

In [22]:
#Centroides

x = df_canciones[['Valencia', 'Energía']].to_numpy()
y = df_canciones['Explícito']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.4)

In [23]:
modelo_kmeans = KMeans(n_clusters = 10, n_init=40).fit(x_train)
centroides = modelo_kmeans.cluster_centers_
#print(centroides)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13684\1669443082.py:1: ConvergenceWarning: Number of distinct clusters (4) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  modelo_kmeans = KMeans(n_clusters = 10, n_init=40).fit(x_train)

In [24]:
def recomiendameCanciones(listaDeCanciones,datosCanciones,cancionEjemplo,centroides):
    #Vamos a buscar el centroide mas cercano
    clasificacionDeseada = centroideCercano(cancionEjemplo, centroides)
    
    #Luego, vamos a clasificar todas las canciones por centroides.
    clasificaciones = clasificarPorCentroides(datosCanciones, centroides)
    
    #Finalmente, sacaremos los indices que hacen match entre clasificaciones.
    indices = np.where(clasificaciones == clasificacionDeseada)[0]
    
    #Y regresamos la lista de peliculas.
    return listaDeCanciones[indices]

In [25]:
#Sientete libre de cambiar este valor.
indice_df = 9

#Extrae la película que deseas del dataframe.
cancionElegida = df_canciones.iloc[indice_df]

#Obten las características de la pelicula que elegiste.
caracteristicaCancion = cancionElegida[['Valencia', 'Energía']].to_numpy()

#Obten la lista de recomendaciones
recomendaciones = recomiendameCanciones(df_canciones['Nombre'],x, caracteristicaCancion, centroides)

#E imprime lo que hallaste!
print("Porque escuchaste "+cancionElegida['Nombre']+" ...")
print(recomendaciones)

Porque escuchaste Il Etait Syndiqué ...
1                           Clancy Lowered the Boom
8                       La Mañanita - Remasterizado
9                                 Il Etait Syndiqué
10                  Dans La Vie Faut Pas S'en Faire
11               Por Que Me Dejaste - Remasterizado
                            ...
170549    The Man, The Myth, The Legend - Interlude
170579                           Internet Ruined Me
170601                          Que Fue Lo Que Paso
170618                                   What It Is
170646                       NASTY GIRL / ON CAMERA
Name: Nombre, Length: 39331, dtype: object

### Regresión Lineal

In [26]:
# Predecir el precio del oro, usando como entradas los valores que obtuvo en los ultimos 10 años
df.head(4)

       Fecha  Precio  Apertura  Máximo  Mínimo
0 2013-01-02  1689.9    1675.8  1695.0  1672.1
1 2013-01-03  1675.6    1688.0  1689.3  1664.3
2 2013-01-04  1649.9    1664.4  1664.4  1630.0
3 2013-01-07  1647.2    1657.3  1663.8  1645.3

In [27]:
# El dato a predecir es Precio, por lo que se definen las siguientes variable independientes y dependiente:
X = df[['Apertura', 'Máximo', 'Mínimo']]
Y = df['Precio']

In [28]:
# División de datos en para entrenamiento-prueba y entrenamiento del regresor lineal
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.4, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(1549, 3)
(1034, 3)
(1549,)
(1034,)

In [29]:
# Entrenamiento y predicciones
lin_model = LinearRegression()
lin_model.fit(X_train, Y_train)

LinearRegression()

In [30]:
y_train_predict = lin_model.predict(X_train)
MSE = mean_squared_error(Y_train,y_train_predict)
print("Entrenamiento: MSE ="+str(MSE))

y_test_predict = lin_model.predict(X_test)
MSE = (mean_squared_error(Y_test, y_test_predict))
print("Pruebas: MSE ="+str(MSE))

Entrenamiento: MSE =29.33762883879572
Pruebas: MSE =28.805792822667094

In [31]:
# Predicciones
df_predicciones = pd.DataFrame({'valor_real':Y_test, 'prediccion':y_test_predict})
df_predicciones = df_predicciones.reset_index(drop = True)
df_predicciones.head(10)

   valor_real   prediccion
0      1106.6  1109.644264
1      1792.3  1795.148161
2      1784.3  1789.476003
3      1799.3  1792.513659
4      1179.8  1182.029698
5      1838.8  1839.888902
6      1128.0  1125.049375
7      1572.8  1572.850705
8      1772.8  1775.235090
9      1292.1  1286.491871

### Regresión Lineal Vs Regresión Polinomial

In [32]:
# Se utilizara el mismo dataFrame:
X = df[['Apertura', 'Máximo', 'Mínimo']]
Y = df['Precio']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.4, random_state=5)

In [33]:
# Regresión Lineal - Error Cuadratico Medio (MSE)
lin_model = LinearRegression()
lin_model.fit(X_train, Y_train)
y_train_predict = lin_model.predict(X_train)
MSE = mean_squared_error(Y_train,y_train_predict)
print("Entrenamiento: MSE ="+str(MSE))

y_test_predict = lin_model.predict(X_test)
MSE = (mean_squared_error(Y_test, y_test_predict))
print("Pruebas: MSE ="+str(MSE))

df_predicciones = pd.DataFrame({'valor_real':Y_test, 'prediccion':y_test_predict, 'diferencia':Y_test-y_test_predict})
df_predicciones = df_predicciones.reset_index(drop = True)
df_predicciones.head(10)

Entrenamiento: MSE =29.33762883879572
Pruebas: MSE =28.805792822667094

   valor_real   prediccion  diferencia
0      1106.6  1109.644264   -3.044264
1      1792.3  1795.148161   -2.848161
2      1784.3  1789.476003   -5.176003
3      1799.3  1792.513659    6.786341
4      1179.8  1182.029698   -2.229698
5      1838.8  1839.888902   -1.088902
6      1128.0  1125.049375    2.950625
7      1572.8  1572.850705   -0.050705
8      1772.8  1775.235090    -2.43509
9      1292.1  1286.491871    5.608129

In [34]:
# Regresión Polinomial (Grado 2) - Error Cuadratico Medio (MSE)
poly_model = LinearRegression()
poly = PolynomialFeatures(degree=2)

Xpolytrain = poly.fit_transform(X_train)
Xpolytest = poly.fit_transform(X_test)

poly_model.fit(Xpolytrain, Y_train)
y_train_predict = poly_model.predict(Xpolytrain)

MSE = mean_squared_error(Y_train,y_train_predict)
print("Entrenamiento: MSE ="+str(MSE))

y_test_predict = poly_model.predict(Xpolytest)
MSE = (mean_squared_error(Y_test, y_test_predict))
print("Pruebas: MSE ="+str(MSE))

df_predicciones = pd.DataFrame({'valor_real':Y_test, 'prediccion':y_test_predict, 'diferencia':Y_test-y_test_predict})
df_predicciones = df_predicciones.reset_index(drop = True)
df_predicciones.head(10)

Entrenamiento: MSE =29.024270741226236
Pruebas: MSE =28.60142102570497

   valor_real   prediccion  diferencia
0      1106.6  1110.081647   -3.481647
1      1792.3  1795.391325   -3.091325
2      1784.3  1789.139796   -4.839796
3      1799.3  1792.511857    6.788143
4      1179.8  1182.431066   -2.631066
5      1838.8  1840.036605   -1.236605
6      1128.0  1125.202960     2.79704
7      1572.8  1572.827667   -0.027667
8      1772.8  1775.499783   -2.699783
9      1292.1  1286.638128    5.461872

### Árboles de Decisión

In [35]:
# Análisis químico de vinos que han crecido en una misma región en Italia
from sklearn.datasets import load_wine
# Carga el conjunto de datos de vino
dataset = load_wine()
x, y = dataset.data, dataset.target


df_vinos = pd.DataFrame(x, columns=dataset.feature_names)
df_vinos['Vinicultor'] = y

In [36]:
# Divide el DataFrame en características (X) y Vinicultor (y)
X = df_vinos.drop('Vinicultor', axis=1)
y = df_vinos['Vinicultor']

In [37]:
# Se divide el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
# Crea el clasificador Random Forest
clf = RandomForestClassifier(n_estimators = 10, random_state=42)

In [39]:
# Entrenamiento del clasificador
clf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10, random_state=42)

In [40]:
# Se realizan las predicciones en el conjunto de prueba
y_pred = clf.predict(X_test)

In [41]:
# Calcula la precisión del clasificador
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del clasificador Random Forest:", accuracy)

Precisión del clasificador Random Forest: 0.9444444444444444

In [42]:
df_result = pd.concat([X_test, y_test, pd.DataFrame({'Predicciones': y_pred})], axis=1)
# Imprimir la tabla
print(df_result)

     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
19     13.64        3.10  2.56               15.2      116.0           2.70
45     14.21        4.04  2.44               18.9      111.0           2.85
140    12.93        2.81  2.70               21.0       96.0           1.54
30     13.73        1.50  2.70               22.5      101.0           3.00
67     12.37        1.17  1.92               19.6       78.0           2.11
..       ...         ...   ...                ...        ...            ...
28       NaN         NaN   NaN                NaN        NaN            NaN
32       NaN         NaN   NaN                NaN        NaN            NaN
33       NaN         NaN   NaN                NaN        NaN            NaN
34       NaN         NaN   NaN                NaN        NaN            NaN
35       NaN         NaN   NaN                NaN        NaN            NaN

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
19         3.03                  0.17             1.66             5.10  0.96
45         2.65                  0.30             1.25             5.24  0.87
140        0.50                  0.53             0.75             4.60  0.77
30         3.25                  0.29             2.38             5.70  1.19
67         2.00                  0.27             1.04             4.68  1.12
..          ...                   ...              ...              ...   ...
28          NaN                   NaN              NaN              NaN   NaN
32          NaN                   NaN              NaN              NaN   NaN
33          NaN                   NaN              NaN              NaN   NaN
34          NaN                   NaN              NaN              NaN   NaN
35          NaN                   NaN              NaN              NaN   NaN

     od280/od315_of_diluted_wines  proline  Vinicultor  Predicciones
19                           3.36    845.0         0.0           1.0
45                           3.33   1080.0         0.0           NaN
140                          2.31    600.0         2.0           NaN
30                           2.71   1285.0         0.0           0.0
67                           3.48    510.0         1.0           NaN
..                            ...      ...         ...           ...
28                            NaN      NaN         NaN           1.0
32                            NaN      NaN         NaN           2.0
33                            NaN      NaN         NaN           0.0
34                            NaN      NaN         NaN           0.0
35                            NaN      NaN         NaN           0.0

[62 rows x 15 columns]

### Redes Neuronales Artificiales

In [43]:
# Red neuronal que permite realizar la separación en dos clases de un dataset de prueba.
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_breast_cancer

# Carga del conjunto de datos
dataset = load_breast_cancer()
x, y = dataset.data, dataset.target

In [44]:
# Dividiendo el conjutno de datos para entrenamiento y prueba.
# Red neuronal de 3 neuronas en una capa y 1 para clasificación binaria
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.4)

redNeuronal = MLPClassifier(hidden_layer_sizes=(3,1),
                            max_iter=20000,
                            activation ='logistic',
                            tol= 1e-7)

redNeuronal.fit(x_train, y_train)
y_pred = redNeuronal.predict(x_test)
print("Entrenamiento completado!")

Entrenamiento completado!

### Matriz de Confusión y Métricas de Desempeño

In [45]:
# Imprimiendo Matriz de Confusión por medio de la funcion matriz_confusion
TP, TN, FP, FN = matriz_confusion(y_test, y_pred)

# Imprimiendo Métricas de Desempeño por medio de las funciones Accuracy, Sensibilidad y Especificidad
acc = calcularAccuracy(TP, TN, FP, FN)
print("\nPrecision:"+str(acc)+"%")

sen = calcularSensibilidad(TP, TN, FP, FN)
print("Sensibilidad:"+str(sen)+"%")

spec = calcularEspecificidad(TP, TN, FP, FN)
print("Especificidad:"+str(spec)+"%")

[[ 76   4]
 [  9 139]]

True positives: 139
True negatives: 76
False positives: 4
False negative: 9

Precision:94.2982456140351%
Sensibilidad:93.91891891891892%
Especificidad:95.0%

### Comparativa de Clasificadores

In [ ]:
# Clasificar un dataset binario para la detección del cancer
# Carga del conjunto de datos
dataset_cancer = load_breast_cancer()
x, y = dataset_cancer.data, dataset_cancer.target

In [46]:
# Dividiendo el conjutno de datos para entrenamiento y prueba.
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.4)

### Naïve Bayes:

In [47]:
from sklearn.naive_bayes import GaussianNB
NaiveBayes = GaussianNB()
NaiveBayes.fit(x_train, y_train) 
y_pred_nb = NaiveBayes.predict(x_test)

In [48]:
# Imprimiendo Matriz de Confusión por medio de la funcion matriz_confusion
TP, TN, FP, FN = matriz_confusion(y_test, y_pred_nb)

# Imprimiendo Métricas de Desempeño por medio de las funciones Accuracy, Sensibilidad y Especificidad
acc = calcularAccuracy(TP, TN, FP, FN)
print("\nPrecision:"+str(acc)+"%")

sen = calcularSensibilidad(TP, TN, FP, FN)
print("Sensibilidad:"+str(sen)+"%")

spec = calcularEspecificidad(TP, TN, FP, FN)
print("Especificidad:"+str(spec)+"%")

[[ 79   9]
 [  3 137]]

True positives: 137
True negatives: 79
False positives: 9
False negative: 3

Precision:94.73684210526315%
Sensibilidad:97.85714285714285%
Especificidad:89.77272727272727%

### Support Vector Machine:

In [49]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline

SupportVectorMachine = SVC()
SupportVectorMachine.fit(x_train, y_train) 
y_pred_svm = SupportVectorMachine.predict(x_test)

In [50]:
# Imprimiendo Matriz de Confusión por medio de la funcion matriz_confusion
TP, TN, FP, FN = matriz_confusion(y_test, y_pred_svm)

# Imprimiendo Métricas de Desempeño por medio de las funciones Accuracy, Sensibilidad y Especificidad
acc = calcularAccuracy(TP, TN, FP, FN)
print("\nPrecision:"+str(acc)+"%")

sen = calcularSensibilidad(TP, TN, FP, FN)
print("Sensibilidad:"+str(sen)+"%")

spec = calcularEspecificidad(TP, TN, FP, FN)
print("Especificidad:"+str(spec)+"%")

[[ 73  15]
 [  2 138]]

True positives: 138
True negatives: 73
False positives: 15
False negative: 2

Precision:92.54385964912281%
Sensibilidad:98.57142857142858%
Especificidad:82.95454545454545%

### Redes Neuronales Artificiales:

In [51]:
NeuralNetwork = MLPClassifier(hidden_layer_sizes=(10,4),
                            max_iter=20000,
                            activation ='logistic',
                            tol= 1e-8)

NeuralNetwork.fit(x_train, y_train)
y_pred_nn = NeuralNetwork.predict(x_test)

In [52]:
# Imprimiendo Matriz de Confusión por medio de la funcion matriz_confusion
TP, TN, FP, FN = matriz_confusion(y_test, y_pred_nn)

# Imprimiendo Métricas de Desempeño por medio de las funciones Accuracy, Sensibilidad y Especificidad
acc = calcularAccuracy(TP, TN, FP, FN)
print("\nPrecision:"+str(acc)+"%")

sen = calcularSensibilidad(TP, TN, FP, FN)
print("Sensibilidad:"+str(sen)+"%")

spec = calcularEspecificidad(TP, TN, FP, FN)
print("Especificidad:"+str(spec)+"%")

[[ 80   8]
 [  6 134]]

True positives: 134
True negatives: 80
False positives: 8
False negative: 6

Precision:93.85964912280701%
Sensibilidad:95.71428571428572%
Especificidad:90.9090909090909%

### Random Forests:

In [53]:
RandomForest = RandomForestClassifier(n_estimators = 800)
RandomForest.fit(x_train, y_train)
y_pred_rfc = RandomForest.predict(x_test)

In [54]:
# Imprimiendo Matriz de Confusión por medio de la funcion matriz_confusion
TP, TN, FP, FN = matriz_confusion(y_test, y_pred_rfc)

# Imprimiendo Métricas de Desempeño por medio de las funciones Accuracy, Sensibilidad y Especificidad
acc = calcularAccuracy(TP, TN, FP, FN)
print("\nPrecision:"+str(acc)+"%")

sen = calcularSensibilidad(TP, TN, FP, FN)
print("Sensibilidad:"+str(sen)+"%")

spec = calcularEspecificidad(TP, TN, FP, FN)
print("Especificidad:"+str(spec)+"%")

[[ 80   8]
 [  4 136]]

True positives: 136
True negatives: 80
False positives: 8
False negative: 4

Precision:94.73684210526315%
Sensibilidad:97.14285714285714%
Especificidad:90.9090909090909%

### Procesamiento de Imágenes